# Generated by Django 3.2.6 on 2021-09-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_incharge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incharge',
            name='branch_field',
        ),
        migrations.RemoveField(
            model_name='incharge',
            name='contact_field',
        ),
        migrations.RemoveField(
            model_name='incharge',
            name='email_field',
        ),
        migrations.RemoveField(
            model_name='incharge',
            name='semester_field',
        ),
        migrations.AddField(
            model_name='incharge',
            name='branch',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='incharge',
            name='contact_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='incharge',
            name='email_id',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='incharge',
            name='semester',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
