# Generated by Django 3.2.6 on 2021-09-05 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210905_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incharge',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='incharge',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='incharge',
            name='email_id',
        ),
        migrations.RemoveField(
            model_name='incharge',
            name='semester',
        ),
        migrations.CreateModel(
            name='club',
            fields=[
                ('club_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('club_description', models.TextField()),
                ('club_incharge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.incharge')),
            ],
        ),
    ]
