# Generated by Django 3.2.6 on 2021-09-05 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210905_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='incharge',
            name='datas',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.userdata'),
        ),
    ]
