# Generated by Django 3.2.6 on 2021-09-05 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_incharge_datas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incharge',
            name='datas',
        ),
    ]
