# Generated by Django 3.2.6 on 2021-09-05 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_incharge_datas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='club_incharge',
            new_name='club_incharge_name',
        ),
    ]
