# Generated by Django 3.2.6 on 2021-09-05 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_club_incharge_club_club_incharge_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='club_incharge_name',
            new_name='club_incharge',
        ),
    ]
