# Generated by Django 3.2.7 on 2021-09-29 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_club_incharge_name_club_club_incharge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gaming',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=30, null=True)),
                ('semester', models.CharField(max_length=10, null=True)),
                ('contact_number', models.CharField(max_length=10, null=True)),
                ('email_id', models.EmailField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='club',
            name='club_incharge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.incharge'),
        ),
    ]
