# Generated by Django 3.2.7 on 2021-09-29 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210929_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_incharge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.incharge'),
        ),
    ]
