# Generated by Django 3.2.7 on 2021-09-29 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_club_club_incharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_incharge',
            field=models.ForeignKey(blank=True, default='None', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='home.incharge'),
        ),
    ]
